aws_region     = "us-east-1"
my_ip_cidr     = "203.0.113.25/32"
db_username    = "admin"
db_password    = "password"
key_name       = "keypair-vpc1"
s3_bucket_name = "nealb03-frontend-bucket-unique-2887"